language: node_js
node_js:
  - "4"
  - "5"
  - "6"

# Use faster Docker architecture on Travis.
sudo: false

script: npm test

addons:
  code_climate:
    repo_token: ba9cf96edbf3cdfd475fa87afa6261f5f5296050214247e0f34c09e3a8ba98c2
